Completed the confirmation email functionality
lacf95/EthermineApp pull request #14
Opened 2018-02-19 23:17 UTC by lacf95

- Email with confirmation email
- Error validation on non exist token

2018-02-19 23:43 UTC, cesargomez89 commented on app/controllers/registration_controller.rb
> +  def confirm_url
you can use path helper passign the token as parameter

2018-02-19 23:44 UTC, cesargomez89 commented on app/controllers/registration_controller.rb
> +  def confirm_url
`anything_path(token)`

2018-02-19 23:44 UTC, cesargomez89 requested changes
I left 1 comment

2018-02-20 15:10 UTC, lacf95 commented
Updated now

2018-02-20 16:29 UTC, cesargomez89 approved these changes

2018-02-20 16:29 UTC, merged